# fly.toml app configuration file
app = "docker-demo-showcase"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  DOCKER_HUB_USERNAME = "murr2k"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"